name: {%project_name%}
recipe: drupal8
config:
  php: 7.1
  webroot: web
  drush: composer
  drupal: true
  database: mysql
  xdebug: true
services:
  database:
    type: mysql:5.7
  node-cli:
    type: 'node:6.10'
    globals:
      gulp-cli: latest
  pma:
    type: phpmyadmin
tooling:
  npm:
    service: node-cli
  drupal:
    cmd:
      - "/app/vendor/bin/drupal"
      - "--root=/app/web"
  phplint:
    service: appserver
    cmd: /app/vendor/bin/phplint
  phpcs:
    service: appserver
    cmd: /app/vendor/bin/phpcs
  phpunit:
    service: appserver
    cmd: /app/vendor/bin/phpunit
